# Generated by Django 5.2.7 on 2025-11-30 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="estimated_hrs",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0.5)]
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="importance",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
    ]
